version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: arqsys-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: arqsys
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
